### PR TITLE
added searchbar functionality to Leaderboard

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
Issue resolved : #74 

Features added :- 
- searchBar with totalCount of rows in table at present.
- Clicking on search btn when empty search string will return all data.
- Will search when either button is clicked or enter key is released.
- Responsive

**Additional Note :-** *Noticed that the table was not in the center. Fixed it!*

Please find below a short video for reference

https://user-images.githubusercontent.com/54144759/163707485-1fb61a41-26b5-4623-945c-ce579a328869.mp4

**If possible would love to use this feature live after another server update at midnight 💯**

--------------------------------

**Feature proposal** :- 
There is no loader for the leaderboard at the moment due to which one really doesn't know if anything is happening in the page till the table is populated. Especially when the server is updating, no data is fetched due to which the user might think there is some issue with the page. We can show appropriate messages according to the situation. It will help.

### CODE REVIEW

**Comment by Suvraneel** [comment]
@GaganpreetKaurKalsi  It looks very cool...
Just 1 thing... Its not blending properly with the theming...

Do one thing:
Just change the color scheme according to the light dark theming trigger, then I'll go merge it as a level 3 PR 
🚀

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi It looks very cool... The functionality is perfect... Just 1 thing... Its not blending properly with the theming UI...
> 
> Do one thing: Just change the color scheme according to the light dark theming trigger, then I'll go merge it as a level 3 PR 🚀 :octocat: In the following format:
> 
> ```js
>  {(theme==="dark")? < DarkSearchBar />: <LiteModeSearchBar />} 
> ```

Ya sure! Would you like shades of black or orange ?

Something like this ?
image

**Comment by GaganpreetKaurKalsi** [comment]
**Hope it looks good now :octocat:**

<br>

image

image

**Comment by Suvraneel** [comment]
@GaganpreetKaurKalsi  Perfect 🚀 :octocat: 💯 

Regarding this:
```
Feature proposal :-
There is no loader for the leaderboard at the moment due to which one really doesn't know if anything is happening in the page till the table is populated. Especially when the server is updating, no data is fetched due to which the user might think there is some issue with the page. We can show appropriate messages according to the situation. It will help.
```

There was a loader but I removed it when porting the leaderboard from MUI to TailWind.
Feel free to add one... Create a new issue though ... with the following:

1.  Loader/Spinkit/Skeleton for the leaderboard page before data gets fetched
2.  Also,  A Confetti effect 🎊  would also look noice immediately after it gets loaded... (if you can manage) 🎊

**Comment by GaganpreetKaurKalsi** [comment]
Reloaded the website and thought I loaded my localhost after seeing the searchBar there.
Thanks for merging.
Will open another issue for that for sure, thanks!

**Pull request merged**
