### PR TITLE
Implemented the template in Share badge option

### LINKED ISSUE #269: Shareable badge to social Media
A sharable button which leads user to share badge achievement on the social media.

https://www.loom.com/share/8aef17ac1a5b4b2b9c40853e874cd5b6?sid=98619834-7a22-4085-ab00-5321570cf621

### LINKED ISSUE #320: Sharing Badges
Continued Issue #269 

@sanjay-kv I have successfully made it to paste the badge onto a template. ( I was facing issue for past 2 days because I was specifying the badge path wrong, as the path accessed by node are very confusing in this project and the error was very hard to troubleshoot)

Can you specify what information to provide on that template so that I can create a final template.

### PR DESCRIPTION
**Pull request by partha120804**
the new share-badge.png 

fixes #320 ( also closes #269 )

Share Badge

### CODE REVIEW

**Comment by partha120804** [comment]
the profile picture is cropped in the previous pic, updated the code to resize the profile picture

Share Badge (2)

**Comment by partha120804** [comment]
@sanjay-kv please check this PR, and if you want to suggest some improvements.

**Review by sanjay-kv — APPROVED** [review]
Awesome Development.

**Comment by sanjay-kv** [comment]
i merged the changes, in local i could see the change. could you see the change in the main website.? @partha120804

**Comment by partha120804** [comment]
no, its not working on main website

**Comment by partha120804** [comment]
@sanjay-kv just noticed that when i raised the PR to add the share buttons in light theme, thats also not visible on main website, its only showing share button in dark theme till now

**Comment by sanjay-kv** [comment]
but dark theme only gives badge image

**Comment by partha120804** [comment]
yeah when i created the PR i forgot to add it to the light theme, 
so the website is showing the elements updated in PR #316 but not anything after it. Not even #318

**Comment by sanjay-kv** [comment]
@Hemu21 can you look into that. 
The new changes i could see in the codespace while running, but when merge its not reflecting on the website .
Is it because of the recent build fail issues.

**Comment by partha120804** [comment]
Yeah the changes are now visible on the webpage @sanjay-kv

**Pull request merged**
