### PR TITLE
Improved the Leaderboard Stats

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have created the leaderboard like shown in the image 

closes : #293 

image

https://github.com/user-attachments/assets/bb9ce8b1-39e2-47e2-85ba-6d2be4ab5945

Sir i have created a functional leaderboard and have used a github api endpoints but these have limited access 
If you found any mistake or want to change anything then please let me know

### CODE REVIEW

**Comment by sanjay-kv** [comment]
the placement was wrong
image
image

**Comment by Ayushmaanagarwal1211** [comment]
> the placement was wrong image image

ok sir i will fix i thought that i have to change the modal

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir i have updated the code like i am opening the stats modal when user will click on the image of the contributor


https://github.com/user-attachments/assets/9346cb47-f826-400c-a2c9-ddc25fb072ef

Sir i have placed at the image because on clicking the github username it is opening the profile so i added this at image

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir i have updated the code like i am opening the stats modal when user will click on the image of the contributor


https://github.com/user-attachments/assets/9346cb47-f826-400c-a2c9-ddc25fb072ef

Sir i have placed at the image because on clicking the github username it is opening the profile so i added this at image

**Comment by sanjay-kv** [comment]
one more small change. 
image

can we take user to different URL , like profile URL. ?

**Comment by Ayushmaanagarwal1211** [comment]
> one more small change. image
> 
> can we take user to different URL , like profile URL. ?
> 
> a separate URL page for each user so they can go directly to that page? sorry for not communicating the requirement before

yes sir i will

**Comment by Ayushmaanagarwal1211** [comment]
> one more small change. image
> 
> can we take user to different URL , like profile URL. ?
> 
> a separate URL page for each user so they can go directly to that page? sorry for not communicating the requirement before



> one more small change. image
> 
> can we take user to different URL , like profile URL. ?
> 
> a separate URL page for each user so they can go directly to that page? sorry for not communicating the requirement before

Yes sir i can but for that i need to create a seperate page and fetch all api's in that page and have to remove the changes i did on modal 
If you want i can do it

**Comment by sanjay-kv** [comment]
Yes if you can

**Comment by Ayushmaanagarwal1211** [comment]
> Yes if you can

Ok sir

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Done Sir



https://github.com/user-attachments/assets/80502e6a-bfc9-4812-8a32-5c43c3e13743

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
could you work around this
https://github.com/girlscript/gssoc-website-new/actions/runs/10017818071

**Comment by Ayushmaanagarwal1211** [comment]
> could you work around this https://github.com/girlscript/gssoc-website-new/actions/runs/10017818071

Yes sir i am checking

**Pull request merged**
