### PR TITLE
Updated gssoc to gssoc extd and timelines

### PR DESCRIPTION
**Pull request by Meetjain1**
Closes [issue 1](https://github.com/GSSoC24/being-an-GSSoc24/issues/165)
Closes [issue 2](https://github.com/GSSoC24/being-an-GSSoc24/issues/139)

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Review by Hemu21 — CHANGES_REQUESTED** [review]
Not only main page you can check the remaining pages and change those from gssoc to gssoc extd

**Review by MastanSayyad — APPROVED** [review]

**Comment by Meetjain1** [comment]
> Not only main page you can check the remaining pages and change those from gssoc to gssoc extd

@Hemu21 I saw other pages but ig its not required bz in project page whenever gssoc extd projects will add it can be changed remaining i dont think so I left out with any , let me know where I should change if any.

**Comment by Meetjain1** [comment]
@Hemu21 also updated timelines

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by Hemu21 — APPROVED** [review]

**Review by suhanipaliwal — APPROVED** [review]

**Comment by Meetjain1** [comment]
@Hemu21 pr is ready to merge

**Pull request merged**
