### PR TITLE
Added Share and Download Button to the Badges

### LINKED ISSUE #269: Shareable badge to social Media
A sharable button which leads user to share badge achievement on the social media.

https://www.loom.com/share/8aef17ac1a5b4b2b9c40853e874cd5b6?sid=98619834-7a22-4085-ab00-5321570cf621

### PR DESCRIPTION
**Pull request by partha120804**
On hovering on the badges one can find the share button and download button.

image

Closes #269

### CODE REVIEW

**Comment by partha120804** [comment]
@sanjay-kv 

I saw that video example you have given, but apparently Linkedin no longer allows to share image files via web api. And adding a customized button for only Twitter didn't make sense, so added a native share button that will share the image through your os and can be shared to all your installed apps, and on the side added a download button so that the user can download the badge and share it manually or just store it.

**Comment by partha120804** [comment]
@sanjay-kv please review and merge the pr and tell me if there are any changes/improvements you will like

**Comment by partha120804** [comment]
@sanjay-kv ??

**Comment by sanjay-kv** [comment]
Sorry couldn't able to review it yet. I will do it today .

**Comment by partha120804** [comment]
Okay 😄 Please do it when you are free

**Comment by sanjay-kv** [comment]
image
The shareable badge not appearing.

**Comment by sanjay-kv** [comment]
image
Shareable badge only appearing in dark mode. 

image

**Comment by sanjay-kv** [comment]
+ the current implemenation is not what we expected. 

1. is there any way we can make it dynamic? like fetching the image of the user photo and putting it on the default image which we provide for certain badge?
2. 
image
something like this. we create a template for each banner on canvas and rather than downloading image. 

We will fetch and paste users photo on the template dynamic?

**Review by sanjay-kv — APPROVED** [review]

**Comment by partha120804** [comment]
> Shareable badge only appearing in dark mode

sorry for that I didn't see there are different pages for diferent themes, will update it with a new PR immediately

**Comment by partha120804** [comment]
> something like this. we create a template for each banner on canvas and rather than downloading image.
> 
> We will fetch and paste users photo on the template dynamic?

Yeah it is possible, I will try to implement it.

**Pull request merged**
