### PR TITLE
registration page front end part

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
will send video regarding this for now just uploading the pull request please dont merge it

### CODE REVIEW

**Comment by sanjay-kv** [comment]
can u add the issue u refering to as well @aditya-bhaumik

**Comment by aditya-bhaumik** [comment]
https://github.com/orgs/GSSoC24/projects/2/views/1?filterQuery=assignee%3A%22aditya-bhaumik%22&pane=issue&itemId=79009190

sorry i am really busy in college placement hemanth and mastan told it was urgent so created the pull request as soon as possible


will be free at 4 will upload the video for this pull request

**Comment by MastanSayyad** [comment]
image

image

image

@sanjay-kv

**Review by sanjay-kv — APPROVED** [review]

**Review by MastanSayyad — APPROVED** [review]

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@Hemu21 dont merge this pull request yet there is one small update left to do 
then i will send the video of how the registration works

**Comment by aditya-bhaumik** [comment]
https://github.com/user-attachments/assets/746f28de-76ce-416e-b5ea-8225cf10c528

it is working properly now just one problem is the pop up keeps coming i tried fixing it but cant understand where the component is  i have also fixed the problem where when we click on mentor it was still opening the registration page in the last commit 

sorry its not there in the video but i have added a conditional statement to solve that problem

**Review by suhanipaliwal — APPROVED** [review]

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@aditya-bhaumik go to `components/PopupBanner.js`

 You can conditionally render the pop-up banner based on the route. add logic to exclude certain routes from displaying the banner.

**Comment by aditya-bhaumik** [comment]
@MastanSayyad i tried it 

was giving error for some reason i introduced a use state condition for it but it did not work 

still let me try once again

**Comment by MastanSayyad** [comment]
@Hemu21 @shreyash3087

**Comment by shreyash3087** [comment]
@aditya-bhaumik @MastanSayyad @Hemu21  

I am concerned about a couple of things here,first of all did we change the design of the front end.I believe we had thought of this design for the page- [Figma](https://www.figma.com/design/qixmCUVkQt1e3BY8NjKViI/GSSOC-Reg?node-id=0-1&node-type=CANVAS&t=JNkj9WKMxfsgTC79-0) .

Second thing i had made input fields that could -
1. Take Phone Numbers along with country code.
2. Country Based State Selection  Field 
Is there a reason for them to be removed?

3. Can you confirm if everything is working and the data is still being stored fine in MongoDB
4. Can you confirm about the responsiveness?

**Comment by MastanSayyad** [comment]
@aditya-bhaumik have followed the design given in the figma?

**Comment by shreyash3087** [comment]
@MastanSayyad 
This was the Design ?

Screenshot (627)

**Comment by aditya-bhaumik** [comment]
@shreyash3087 hi i have made it responsive it took some time but i fixed it like i had told on whatsapp 

and the other things i removed some components as they were causing problem with the responsiveness 

the design was not supposed to be followed fully as there is both dark mode and light mode and that design was causing problem in responsiveness 

and my job was only frontend

backend someone else was supposed to take care of so mongodb part i have not done

**Comment by aditya-bhaumik** [comment]
also i talked to hemanth he only wanted the ca page ready now thats why the other pages are showing coming soon @shreyash3087 

i have made the other pages also just have not added them

**Comment by shreyash3087** [comment]
@aditya-bhaumik I had completed the backend already - https://github.com/girlscript/gssoc-website-new/pull/371

I had also made a sample form for all the roles so that the person who was supposed to make the frontend would have ease to just change the layout of the input field and just add the background and other stuff, i believe you missed it and removed everything completely to start adding the frontend from scratch,if you have removed the whole backend and if the form is not working as before,i generally dont say this but we will have to rethink about this PR @MastanSayyad @Hemu21

**Comment by MastanSayyad** [comment]
Hi, @aditya-bhaumik 

Thanks for making it responsive, I appreciate the effort. However, the input fields for phone numbers and country-based state selection were crucial features, and they should not have been removed without discussing alternative solutions. We need to find a way to retain these functionalities while maintaining responsiveness.

As for the design, I understand that implementing dark mode might cause some issues, but we should have followed the original design as closely as possible. If there were problems, we could have addressed them together rather than making changes (tho design is not the issue this will also work)

Regarding MongoDB, even though someone else may handle the backend, ensuring that the front-end components are integrated properly with the backend (like form submissions and data validation) should still be a part of your responsibility. We need to ensure the full functionality of the project.

**Comment by aditya-bhaumik** [comment]
@shreyash3087 well i am in placement training right now you can take care of it please i am assigning the issue also with you when i am done will contact you

**Pull request closed without merging**
