### PR TITLE
feat: Implement Chat System using Firebase

### PR DESCRIPTION
**Pull request by mukilan2815**
This pull request introduces a new chat system for the community, built using Firebase. The chat system allows participants to communicate with each other, ask doubts, share issues they are facing, and exchange files (up to 5MB) within the community platform.

**Features**:
- Real-time messaging using Firebase Realtime Database
- Group chat room for all participants
- Chat interface with a message input field and message display area
- Ability to send text messages
- File sharing support (up to 5MB file size)

**Implementation**:
- Used Firebase Realtime Database to store and sync messages in real-time
- Implemented file upload using Firebase Storage
- Implemented the chat interface using Next js

**Usage**:
1. Navigate to the chat section of the community platform
2. The chat interface will be displayed
3. Type your message in the input field and press enter/send
4. Your message will be visible to all participants in the group chat room
5. To share a file, click the "Attach File" button, select a file (up to 5MB), and send

**Testing**:
- Tested the chat system locally with multiple simulated users
- Verified real-time message synchronization
- Tested file upload and download functionality

**Resolves**: #262

### CODE REVIEW

**Comment by sanjay-kv** [comment]
image


failed to test . can we connect sometime later today to discuss this.

**Comment by mukilan2815** [comment]
did u enter the firebase config?

**Comment by mukilan2815** [comment]
Can you please check it out now? i have added my config.

**Comment by sanjay-kv** [comment]
sure

**Comment by sanjay-kv** [comment]
image


let us connect when you free

**Comment by mukilan2815** [comment]
I am not sure about this issue. in my systems it works fine , let me check once. how to connect you?

**Comment by mukilan2815** [comment]
image
image
image
image
sample screenshots

**Comment by mukilan2815** [comment]
@sanjay-kv Please check it out

**Comment by sanjay-kv** [comment]
could you give me your email ID?

**Comment by mukilan2815** [comment]
mukilan2808@gmail.com

**Comment by sanjay-kv** [comment]
can i connect with you now?

**Comment by mukilan2815** [comment]
7448359935 if free call me bro

**Comment by sanjay-kv** [comment]
you can reach me out on linkedin but we will talk about the things after aug 15. i will sort out gssoc in between

**Pull request closed without merging**
