### PR TITLE
BUG: Fixed the Clear Search button

### LINKED ISSUE #276: Leaderboard Search bar
https://github.com/GSSoC24/Contributor/issues/468#issuecomment-2184684320

### PR DESCRIPTION
**Pull request by partha120804**
changed the search input to a normal text input and added an extra clear input button. 
Now it resets the page when search bar is cleared.

Closes #276

### CODE REVIEW

**Comment by partha120804** [comment]
@sanjay-kv 
Fixed the issue, please check the PR and merge it if it's good enough 😄

**Review by sanjay-kv — APPROVED** [review]
Awesome work

**Comment by partha120804** [comment]
this PR score is not reflecting on gssoc leaderboard ? will it not count in gssoc contribution ?

**Comment by sanjay-kv** [comment]
We wont publish this PR on leaderboard now, as I want to keep this repo unlisted and don't want spams issues to be created. 
I will publish all the Scores 5 days before announcement.

**Comment by partha120804** [comment]
Oh I see, actually thoughtful idea ✨

**Pull request merged**
