### PR TITLE
Fixed 1:1 Mentorship bug

### PR DESCRIPTION
**Pull request by Meetjain1**
closes https://github.com/GSSoC24/being-an-GSSoc24/issues/202
Now the 1:1 Mentorsship button will only appear if there is a topmate link present in any profile and will auto disappear when user moves to other page or other profile , Also It will take user to that particular person profile link only when it click on 1:1 Mentorship button 

https://github.com/user-attachments/assets/e6ec896d-3b97-410a-8748-f0d5082f5d68

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Hemu21

**Comment by vansh-codes** [comment]
Hey @Meetjain1 
now the topmate thing wont be coming as a popup right? Now it will redirect the user to the respective team members topmate page instead of coming up as a popup on the gssoc page itself.. now the user will be redirected to the topmate mentorship booking tab, right??

**Review by aditya-bhaumik — APPROVED** [review]

**Review by sanjay-kv — APPROVED** [review]

**Review by aslams2020 — APPROVED** [review]

**Comment by sanjay-kv** [comment]
> closes [GSSoC24/being-an-GSSoc24#202](https://github.com/GSSoC24/being-an-GSSoc24/issues/202) Now the 1:1 Mentorsship button will only appear if there is a topmate link present in any profile and will auto disappear when user moves to other page or other profile , Also It will take user to that particular person profile link only when it click on 1:1 Mentorship button
> 
>  2024-09-15-21-56-20.mp4

I just saw this, there is a catch . we are not suppose to take anyone out of gssoc website. 
It should be pop up only for that reason im closing this PR.

**Comment by Meetjain1** [comment]
> > closes [GSSoC24/being-an-GSSoc24#202](https://github.com/GSSoC24/being-an-GSSoc24/issues/202) Now the 1:1 Mentorsship button will only appear if there is a topmate link present in any profile and will auto disappear when user moves to other page or other profile , Also It will take user to that particular person profile link only when it click on 1:1 Mentorship button
> > 2024-09-15-21-56-20.mp4
> 
> I just saw this, there is a catch . we are not suppose to take anyone out of gssoc website. It should be pop up only for that reason im closing this PR.

Its a popup button only which I dont added , I just fixed the bug that is it should not appear on other pages . I suggested to remove this button completely in the issue  https://github.com/GSSoC24/being-an-GSSoc24/issues/202 closing this pr will cause the button bug to presist , We should remove this button completely or we should place it as I did in this PR let me know what to do @sanjay-kv

**Comment by vansh-codes** [comment]
@Meetjain1 hi
Can you share one video where you click that button and we see what happens when it's clicked
It would be clear for everyone to understand your changes

**Comment by vansh-codes** [comment]
That's what we don't want bro, we don't want to take the user out of GSSoC website, we want it to appear as a popup on the website itself as it is now

**Comment by Meetjain1** [comment]
> That's what we don't want bro, we don't want to take the user out of GSSoC website, we want it to appear as a popup on the website itself as it is now

Ohk , Thanks fixing it

**Pull request closed without merging**
