### PR TITLE
Addded Seconds to the Countdown with Text to Indicate Hours,Mins,Second

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR adds Seconds to the Countdown with Text to Indicate Hours,Mins,Second

**Preview -** 

screencapture-localhost-3000-registration-2024-09-12-12_14_49

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@MastanSayyad @Hemu21

**Review by Hemu21 — APPROVED** [review]

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
image
@shreyash3087

**Comment by shreyash3087** [comment]
@sanjay-kv sure but if we remove the seconds,as i discussed with @Hemu21 and @MastanSayyad the page looks static untill a min passes,seconds makes the timer look like its working since it updates every second.Although if you want i can remove it

**Comment by sanjay-kv** [comment]
@shreyash3087 oh for me the seconds was not moving on my browser. that's why told to remove if that's the case 
don't remove. just highlight hours minutes and seconds in full

**Comment by shreyash3087** [comment]
@Hemu21 @MastanSayyad can you guys confirm if the seconds is updating every seconds?

screencapture-localhost-3000-registration-2024-09-12-13_07_37

**Review by MastanSayyad — APPROVED** [review]

**Review by Hemu21 — APPROVED** [review]

**Pull request merged**
