### PR TITLE
Review is added.

### PR DESCRIPTION
**Pull request by Hemu21**
## Description

Review website is added.

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
https://life-made-easy.vercel.app  i still see its redirecting to your app. 
My proposal was to built in gssoc URL.

**Comment by Hemu21** [comment]
@sanjay-kv  updated. can you please check when you get free time

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
image
404 error

**Comment by Hemu21** [comment]
@sanjay-kv  it was not merged in the main code base. So 404 error is showing.

**Pull request closed without merging**
