### PR TITLE
Enhanced Pagination Tool

### LINKED ISSUE #281: Making the pagination useful.
We can add a copy of pagination on top of the table, so that you don't have to scroll down to change the page.
we can also add a button to change how many contributors they want on a page ( currently it is fixed to 50). We can add a drop down for 25,50,100,200,500,1000.
we can also make the bottom pagination bar automatically triggering "scroll to top" button.

I want to work under GSSOC24 to add this enhancement.

### PR DESCRIPTION
**Pull request by partha120804**
Added a pagination on top of the table, so that you don't have to scroll down to change the page.

Added a button to change how many contributors they want on a page ( currently it is fixed to 50). added a drop down for  10,25,50,100,200,500,1000.

fixes #281 

Works on my device smoothly.
Also checked for mobile devices.

Removed the search icon from search bar as typing in search bar automatically triggers search so there's no need of a separate button.

PC:
image

Mobile:
image

Please assign me under GSSOC

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
image

I can see we already have pagination on the bottom, adding to the top kinda creating messy layout. I liked the idea of listing rows, maybe if move that to the highlighted area as per image would be great.

**Comment by partha120804** [comment]
🤔 @sanjay-kv The pagination on the bottom of the page is very hard to access,

Because if someone toggles the 500 per page option he will have to scroll very long to access the pagination part, as mobile devices don't have a scroll bar, so it's kind of useful to have pagination at the top of the page,

Can we keep it ???

I can add pagination and search bar in the same row and put the "rows per page" icon within the highlighted area,
I think that will make it less messy ?

**Comment by partha120804** [comment]
@sanjay-kv 
I have commented out the pagination part,
And switched the positions of rows per page and search bar.

Adding the "rows per page" dropdown in the highlighted area looks good on big screens but on mobile devices it's very very bad ☠️, tried some alterations but it's just not suitable, so added that on the left side.

**Comment by sanjay-kv** [comment]
image

i still see the same while code review is it the correct PR?

**Comment by partha120804** [comment]
No, their position have been changed with the recent commit

**Pull request merged**
