### PR TITLE
solved the part for light theme

### PR DESCRIPTION
**Pull request by partha120804**
Update: Fixes #316

### CODE REVIEW

**Comment by partha120804** [comment]
@sanjay-kv this one adds the same  implementation to the light theme

**Comment by sanjay-kv** [comment]
image

**Comment by sanjay-kv** [comment]
yours still in draft let me know when you complete

**Comment by partha120804** [comment]
done

i was trying "dark" class while trouble shooting and forgot to remove those classes, they have been removed 👍🏻

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
