### PR TITLE
Added Team Profile Page🚀

### PR DESCRIPTION
**Pull request by vansh-codes**
Closes: https://github.com/GSSoC24/being-an-GSSoc24/issues/137

WhatsApp Image 2024-09-09 at 11 46 58_4fef1228

image

### CODE REVIEW

**Review by shreyash3087 — APPROVED** [review]

**Comment by sanjay-kv** [comment]
`<script
    src="https://topmate-embed.s3.ap-south-1.amazonaws.com/v1/topmate-embed.js"
    user-profile="https://topmate.io/embed/profile/sanjaykv?theme=D5534D"
    btn-style='{"backgroundColor":"#000","color":"#fff","border":"1px solid #000"}'
    embed-version="v1"
    button-text="Let's Connect"
    position-right="30px"
    position-bottom="30px"
    custom-padding="0px"
    custom-font-size="16px"
    custom-font-weight="500"
    custom-width="200px"
    async=""
    defer=""
  ></script>  
`


could you copy the script on the website this side ? and send me a ss here how it look like  @vansh-codes 
image

**Review by Meetjain1 — APPROVED** [review]

**Comment by sanjay-kv** [comment]
okay could you give me the current script you running, I will make a video tutorial for everyone to follow the same. and how to create a topmate service like that.

**Comment by vansh-codes** [comment]
@sanjay-kv It was the same script you gave
We just want their topmate username

```bash
user-profile="https://topmate.io/sanjaykv/1135910/pay?embed=true&theme=D5534D"
```
Here in place of `sanjaykv` we can dynamically fetch team's topmate id and its done
for example, I did mine
```bash
user-profile="https://topmate.io/vansh_chaurasiya/1135910/pay?embed=true&theme=D5534D"
```

https://github.com/user-attachments/assets/c2ca343f-6344-4b72-b3bd-60c452e7901c

Its ready, just need to replace the username at the mentioned place so we need to collect everyone's topmate id

**Comment by shreyash3087** [comment]
https://topmate.io/shreyash_3087/1201328/pay - Shreyash

**Comment by Hemu21** [comment]
https://topmate.io/hemu21/1195017/pay  - Hemanth

**Comment by vansh-codes** [comment]
https://topmate.io/vansh_chaurasiya/1201859/pay

**Comment by aslams2020** [comment]
https://topmate.io/aslam_sayyad/1201969/pay - Aslam

**Comment by Tejashri-Taral** [comment]
https://topmate.io/tejashri_taral/1202023/pay -Tejashri

**Comment by Tejashri-Taral** [comment]
https://topmate.io/tejashri_taral/1202023/pay - Tejashri

**Comment by MastanSayyad** [comment]
https://topmate.io/mastansayyad/1202080/pay - Mastan Sayyad

**Comment by RadhikaMalpani1702** [comment]
Radhika Malpani - https://topmate.io/radhika_malpani/1202110/pay

**Comment by UppuluriKalyani** [comment]
https://topmate.io/kalyani_uppuluri/1202116/pay - Kalyani

**Comment by aditya-bhaumik** [comment]
https://topmate.io/aditya1/1202127/pay

**Review by aditya-bhaumik — APPROVED** [review]

**Review by MastanSayyad — APPROVED** [review]

**Review by aslams2020 — APPROVED** [review]

**Review by Tejashri-Taral — APPROVED** [review]

**Review by Hemu21 — APPROVED** [review]

**Pull request merged**
