### PR TITLE
Created GSSoC'24 Extended team page

### PR DESCRIPTION
**Pull request by vansh-codes**
Created GSSoC'24 Extended team page

https://github.com/user-attachments/assets/c0456919-e532-4442-b71d-b00f99a10b12

### CODE REVIEW

**Review by Hemu21 — APPROVED** [review]

**Review by suhanipaliwal — APPROVED** [review]

**Review by aditya-bhaumik — APPROVED** [review]

**Review by UppuluriKalyani — APPROVED** [review]

**Review by shreyash3087 — APPROVED** [review]

**Review by MastanSayyad — CHANGES_REQUESTED** [review]
Some of the images are circular, can you fix them? Plus how is it in mobile view? (As initially most of the beginners use mobile more)

**Comment by vansh-codes** [comment]
> Some of the images are circular, can you fix them? Plus how is it in mobile view? (As initially most of the beginners use mobile more)

Mobile view is perfect, and Ig only Aditya's image is circular

**Review by akshithachiluka — APPROVED** [review]

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Comment by aslams2020** [comment]
Hey, the team members' images are following the previous years' format by being outside the main box. 
Could we try changing the format for this extended program to fit the images inside the box? It would give a more structured look...

**Comment by vansh-codes** [comment]
> Hey, the team members' images are following the previous years' format by being outside the main box. Could we try changing the format for this extended program to fit the images inside the box if possible? It would give a more structured look...

Thats a design done purposely i guess, if everyone agrees to make changes as suggested by you so I can !!

**Review by Meetjain1 — APPROVED** [review]

**Review by Tejashri-Taral — APPROVED** [review]

**Review by Meetjain1 — CHANGES_REQUESTED** [review]
@vansh-codes change old logo of twitter to X.

**Review by sanjay-kv — APPROVED** [review]
awesome work

**Comment by vansh-codes** [comment]
> @vansh-codes change old logo of twitter to X.

Done!

**Review by aslams2020 — APPROVED** [review]

**Comment by vansh-codes** [comment]
Updated page:

https://github.com/user-attachments/assets/e4e53270-599d-4e8f-88fc-ee147f7a7f77

**Review by Hemu21 — APPROVED** [review]

**Pull request merged**
